apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: SERVICE_VERSIONS
            value: "v2.0.0"
          - name: ENVIRONMENT
            value: "production"
