apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
  namespace: webapps
spec:
  replicas: 2
  selector:
    app: web
  template:
    metadata:
      name: webserver
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
