apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: webapps
spec:
  replicas: 2
  selector:
    app: nginx-web-apps
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-web-apps
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
  namespace: webapps
spec:
  replicas: 2
  selector:
    app: tomcat-web-apps
  template:
    metadata:
      name: tomcat-rc
      labels:
        app: tomcat-web-apps
    spec:
      containers:
        - name: tomcat
          image: tomcat:latest
          ports:
            - containerPort: 8080