apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: applications
spec:
  containers:
  - name: database
    image: mongo:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017