apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: applications
  labels:
    name: web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80