apiVersion: v1
kind: Pod
metadata:
  name: http
  labels:
    name: webserver
spec:
  containers:
    
    - name: webserver
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "256m"
      ports:
        - containerPort: 80